version: '3.8'

services:
  kunye-qr:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - DEBUG=False
      - PORT=8000
    volumes:
      - ./logs:/app/logs
    container_name: kunye-qr-system
